language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t sandeepb3245/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sandeepb3245/docker-react npm run test